name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: hrdream-frontend

      - name: Run tests
        run: npm run test
        working-directory: hrdream-frontend

    #   - name: Run tests
    #     run: npm test
    #     working-directory: hrdream-frontend

      - name: Build project
        run: npm run build
        working-directory: hrdream-frontend

    #   - name: Deploy to Vercel (example)
    #     uses: amondnet/vercel-action@v20
    #     with:
    #       vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #       vercel-args: "--prod"
    #       working-directory: hrdream-frontend

#   backend:
#     name: Backend CI/CD
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: 3.9

#       - name: Install dependencies
#         run: pip install -r requirements.txt
#         working-directory: HRdreamBackend

#       - name: Lint code
#         run: flake8 .
#         working-directory: HRdreamBackend

#       - name: Run tests
#         run: python manage.py test
#         working-directory: HRdreamBackend

#       - name: Migrate database
#         run: python manage.py migrate
#         working-directory: HRdreamBackend

#       - name: Deploy backend (example for Heroku)
#         uses: akhileshns/heroku-deploy@v4.1.4
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: "your-heroku-app-name"
#           heroku_email: "your-email@example.com"
